name: Python CI with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install system dependencies for building Python packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev

      # 4. Upgrade pip and install AWS CLI
      - name: Install AWS CLI
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade awscli

      # 5. Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install --no-cache-dir --only-binary=:all: -r requirements.txt


      # 6. Run SonarCloud Scan
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: kishore-0501
          projectKey: kishore-0501_farmease
          token: ${{ secrets.SONAR_TOKEN }}
